import { useEffect, useMemo, useState } from "react";
import { approveSchedule, approveScheduleException, downloadSchedulePdf, downloadScheduleXlsx, fetchSchedulingCapabilities, fetchSchedulingProjects, fetchShiftTemplates, generateScheduleProposal, publishSchedule, replanSchedule } from "../../services/portalApi";
import type { CurrentUser, ScheduleAssignment, ScheduleComparison, ScheduleProposal, SchedulingCapabilities, SchedulingProject, ShiftTemplate } from "../../types/portal";
import { ExceptionPanel } from "./ExceptionPanel";
import { ProposalComparison } from "./ProposalComparison";
import { ScheduleMatrix } from "./ScheduleMatrix";
import { ShiftTemplatesPanel } from "./ShiftTemplatesPanel";

interface Props { user: CurrentUser; }
type Tab = "Plantillas" | "Matriz" | "Comparar" | "Excepciones";
const emptyCapabilities: SchedulingCapabilities = { view: false, configure: false, generate: false, approveException: false, approve: false, publish: false, export: false };
const demoCapabilities: SchedulingCapabilities = { view: true, configure: true, generate: true, approveException: true, approve: true, publish: true, export: true };
const demoTemplates: ShiftTemplate[] = [
  { id: 1, code: "2x2", name: "Dos diurnos, dos nocturnos, dos descansos", version: 1, mandatoryByDefault: true, status: "ACTIVO", steps: ["D", "D", "N", "N", "X", "X"].map((shiftCode, index) => ({ order: index + 1, shiftCode: shiftCode as "D" | "N" | "X" })) },
  { id: 2, code: "4x2", name: "Cuatro diurnos, dos nocturnos, dos descansos", version: 1, mandatoryByDefault: true, status: "ACTIVO", steps: ["D", "D", "D", "D", "N", "N", "X", "X"].map((shiftCode, index) => ({ order: index + 1, shiftCode: shiftCode as "D" | "N" | "X" })) },
  { id: 3, code: "6x1", name: "Seis diurnos y un descanso", version: 1, mandatoryByDefault: true, status: "ACTIVO", steps: ["D", "D", "D", "D", "D", "D", "X"].map((shiftCode, index) => ({ order: index + 1, shiftCode: shiftCode as "D" | "N" | "X" })) }
];
const demoProjects: SchedulingProject[] = [{ id: 1, clientId: 1, code: "DEMO", name: "Proyecto demostrativo (sin datos reales)", effectiveFrom: "2026-01-01", effectiveTo: null, status: "ACTIVO" }];

function demoProposal(projectId: number, periodStart: string, periodEnd: string): ScheduleProposal {
  const assignments: ScheduleAssignment[] = Array.from({ length: 21 }, (_, index) => { const employeeId = 101 + (index % 3); const day = 1 + Math.floor(index / 3); const shiftCode = (["D", "N", "X"] as const)[(day + employeeId) % 3]; return { id: index + 1, date: `2026-08-${String(day).padStart(2, "0")}`, startsAt: shiftCode === "N" ? "18:00" : "06:00", endsAt: shiftCode === "N" ? "06:00" : "18:00", positionId: 1, employeeId, shiftCode, status: index === 17 ? "VACANTE" : "ASIGNADA", score: 92 - (index % 7), reasons: [{ code: "TPL", severity: "INFORMATIVA", message: `Coincide con la plantilla cíclica seleccionada.` }] }; });
  return { versionId: 1, scheduleId: 1, projectId, versionNumber: 1, status: "PROPUESTA", periodStart, periodEnd, coveragePercent: 95.2, vacancyCount: 1, exceptionCount: 1, acceptedVacancy: false, createdBy: "demo", approvedBy: null, publishedBy: null, selfManaged: false, assignments, exceptions: [{ id: 1, exceptionType: "REQUISITO_SUBSANABLE", reason: "Ejemplo demostrativo pendiente de soporte.", responsible: "Talento Humano", resolutionDate: "2026-08-05", status: "REGISTRADA" }] };
}

export function SchedulingPage({ user }: Props) {
  const demoMode = new URLSearchParams(window.location.search).get("demo") === "scheduling";
  const [capabilities, setCapabilities] = useState(emptyCapabilities); const [projects, setProjects] = useState<SchedulingProject[]>([]); const [templates, setTemplates] = useState<ShiftTemplate[]>([]);
  const [projectId, setProjectId] = useState<number | "">(""); const [periodStart, setPeriodStart] = useState("2026-08-01"); const [periodEnd, setPeriodEnd] = useState("2026-08-31");
  const [proposal, setProposal] = useState<ScheduleProposal | null>(null); const [selectedAssignment, setSelectedAssignment] = useState<ScheduleAssignment | null>(null); const [scenarios, setScenarios] = useState<ScheduleComparison[]>([]);
  const [tab, setTab] = useState<Tab>("Plantillas"); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const readOnly = proposal?.status === "PUBLICADA";
  const selectedProject = useMemo(() => projects.find((item) => item.id === projectId), [projectId, projects]);

  useEffect(() => { let ignore = false; async function load() { setLoading(true); setError(null); try { if (demoMode) { if (!ignore) { setCapabilities(demoCapabilities); setProjects(demoProjects); setTemplates(demoTemplates); setProjectId(1); } return; } const [nextCapabilities, nextProjects, nextTemplates] = await Promise.all([fetchSchedulingCapabilities(), fetchSchedulingProjects(), fetchShiftTemplates()]); if (!ignore) { setCapabilities(nextCapabilities); setProjects(nextProjects); setTemplates(nextTemplates); } } catch (caught) { if (!ignore) setError(caught instanceof Error ? caught.message : "No fue posible cargar la programación."); } finally { if (!ignore) setLoading(false); } } void load(); return () => { ignore = true; }; }, [demoMode]);

  async function generate() { if (!projectId || !capabilities.generate) return; setBusy(true); setError(null); setMessage(null); try { const next = demoMode ? demoProposal(projectId, periodStart, periodEnd) : await generateScheduleProposal(projectId, { periodStart, periodEnd }); setProposal(next); setSelectedAssignment(next.assignments?.[0] ?? null); setTab("Matriz"); setMessage("Propuesta generada para revisión humana."); } catch (caught) { setError(caught instanceof Error ? caught.message : "No fue posible generar la propuesta."); } finally { setBusy(false); } }
  async function compare() { if (!proposal) return; setBusy(true); try { const next = demoMode ? [{ mode: "MINIMUM_IMPACT", changedAssignments: 3, additionalHours: 4, vacancies: 1, exceptions: 1 }, { mode: "GLOBAL", changedAssignments: 8, additionalHours: 0, vacancies: 0, exceptions: 2 }] as ScheduleComparison[] : (await replanSchedule(proposal.versionId, { triggerType: "MANUAL_REVIEW", triggerId: String(proposal.versionId), modes: ["MINIMUM_IMPACT", "GLOBAL"] })).scenarios; setScenarios(next); setTab("Comparar"); } finally { setBusy(false); } }
  async function registerException(reason: string) { if (!proposal || demoMode) { setMessage(`Desviación demostrativa registrada: ${reason}`); return; } const next = await approveScheduleException(proposal.versionId, { exceptionType: "DESVIACION_PLANTILLA", reason, responsible: user.fullName, resolutionDate: periodEnd, expectedVersion: proposal.versionNumber }); setProposal(next); }
  async function approve() { if (!proposal) return; setBusy(true); try { const next = demoMode ? { ...proposal, status: "APROBADA" as const, approvedBy: user.fullName } : await approveSchedule(proposal.versionId, proposal.versionNumber); setProposal(next); setMessage("Programación aprobada."); } finally { setBusy(false); } }
  async function publish() { if (!proposal) return; setBusy(true); try { const next = demoMode ? { ...proposal, status: "PUBLICADA" as const, publishedBy: user.fullName } : await publishSchedule(proposal.versionId, proposal.versionNumber); setProposal(next); setMessage("Programación publicada en modo de solo lectura."); } finally { setBusy(false); } }
  async function exportFile(format: "pdf" | "xlsx") { if (!proposal) return; setBusy(true); try { if (!demoMode) await (format === "pdf" ? downloadSchedulePdf(proposal.versionId) : downloadScheduleXlsx(proposal.versionId)); else setMessage(`Exportación ${format.toUpperCase()} simulada en modo demostrativo.`); } finally { setBusy(false); } }

  if (loading) return <div className="panel-empty" aria-live="polite">Cargando programación…</div>;
  if (error && projects.length === 0) return <section className="scheduling-workspace"><div className="schedule-alert is-error" role="alert"><strong>No fue posible cargar la programación.</strong><span>{error}</span></div><p className="muted">Verifique la conexión o use <code>?demo=scheduling</code> para el recorrido sin datos reales.</p></section>;

  return <main className="scheduling-workspace">
    <header className="scheduling-hero"><div><p className="eyebrow">Operaciones · Programación asistida</p><h1>Programación de turnos</h1><p>Configure el periodo, revise la propuesta del motor y mantenga la decisión humana trazable.</p></div><div className="hero-status"><span className="schedule-badge">{demoMode ? "MODO DEMO" : proposal?.status ?? "SIN PROPUESTA"}</span><small>{selectedProject?.name ?? "Seleccione un proyecto"}</small></div></header>
    <section className="scheduling-control-bar" aria-label="Filtros de programación"><label>Proyecto<select value={projectId} onChange={(event) => { setProjectId(event.target.value ? Number(event.target.value) : ""); setProposal(null); }}><option value="">Seleccione un proyecto</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Desde<input type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /></label><label>Hasta<input type="date" value={periodEnd} min={periodStart} onChange={(event) => setPeriodEnd(event.target.value)} /></label>{capabilities.generate && <button className="schedule-primary" disabled={!projectId || busy || Boolean(readOnly)} onClick={generate}>{busy ? "Procesando…" : proposal ? "Regenerar propuesta" : "Generar propuesta"}</button>}</section>
    <div className="schedule-live-region" aria-live="polite">{message && <p className="schedule-alert is-success">{message}</p>}{error && <p className="schedule-alert is-error">{error}</p>}</div>
    {proposal && <section className="schedule-summary" aria-label="Resumen de propuesta"><div><span>Cobertura</span><strong>{proposal.coveragePercent}%</strong></div><div><span>Vacantes</span><strong>{proposal.vacancyCount}</strong></div><div><span>Excepciones</span><strong>{proposal.exceptionCount}</strong></div><div><span>Versión</span><strong>v{proposal.versionNumber}</strong></div><div className="summary-actions">{capabilities.approve && proposal.status === "PROPUESTA" && <button onClick={approve} disabled={busy}>Aprobar</button>}{capabilities.publish && proposal.status === "APROBADA" && <button onClick={publish} disabled={busy}>Publicar</button>}{capabilities.export && <><button onClick={() => exportFile("pdf")} disabled={busy}>PDF</button><button onClick={() => exportFile("xlsx")} disabled={busy}>Excel</button></>}{proposal.status === "PUBLICADA" && capabilities.generate && <button onClick={() => { setProposal(null); setTab("Plantillas"); }}>Crear nueva versión</button>}</div></section>}
    <nav className="scheduling-tabs" aria-label="Secciones de programación">{(["Plantillas", "Matriz", "Comparar", "Excepciones"] as Tab[]).map((item) => <button key={item} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {!proposal && tab !== "Plantillas" ? <div className="panel-empty">Seleccione un proyecto y genere una propuesta para continuar.</div> : <>{tab === "Plantillas" && <ShiftTemplatesPanel templates={templates} />}{tab === "Matriz" && proposal && <ScheduleMatrix assignments={proposal.assignments ?? []} readOnly={Boolean(readOnly)} onSelect={setSelectedAssignment} selectedAssignment={selectedAssignment} />}{tab === "Comparar" && proposal && <ProposalComparison scenarios={scenarios} onGenerate={compare} canGenerate={capabilities.generate && !readOnly} busy={busy} />}{tab === "Excepciones" && proposal && <ExceptionPanel exceptions={proposal.exceptions ?? []} capabilities={capabilities} readOnly={Boolean(readOnly)} onSubmit={registerException} />}</>}
  </main>;
}
