[CmdletBinding()]
param([string]$RepositoryRoot)
$ErrorActionPreference='Stop'
$repoRoot=if([string]::IsNullOrWhiteSpace($RepositoryRoot)){(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path}else{(Resolve-Path $RepositoryRoot).Path}
$files=@('apps/sg-superapp-api/Domain/SchedulingRuleModels.cs','apps/sg-superapp-api/Services/SchedulingRuleProfileValidator.cs','apps/sg-superapp-api/Services/SchedulingWorkRestRules.cs','apps/sg-superapp-api/Services/SchedulingOverlapTravelRules.cs','apps/sg-superapp-api/Services/SchedulingRuleEvaluator.cs')|%{Join-Path $repoRoot $_}
$authorizationService=Join-Path $repoRoot 'apps/sg-superapp-api/Services/PortalAuthorizationService.cs'
$authorizationBoundary=Join-Path $repoRoot 'apps/sg-superapp-api/Endpoints/PortalEndpoints.cs'
if(@(($files+$authorizationService+$authorizationBoundary)|?{-not(Test-Path -LiteralPath $_ -PathType Leaf)}).Count){Write-Output 'I9 R03 R05 FAIL: required source missing';exit 1}
$rules=Get-Content $files[3] -Raw;$evaluator=Get-Content $files[4] -Raw
foreach($p in @('EvaluateR03\s*\(','EvaluateR05\s*\(','OVERLAP_APPROVED_BLOCKED.*OVERLAP_DRAFT_BLOCKED','proposedStart\.ToUniversalTime\(\).*previousEnd\.ToUniversalTime\(\)','MATRIX_UNAVAILABLE','INVALID_MATRIX')){if($rules-notmatch("(?s)"+$p)){Write-Output "I9 R03 R05 FAIL: contract $p";exit 1}}
if($evaluator-notmatch 'previousAssignmentId' -or $evaluator-notmatch 'previousShiftEnd' -or $evaluator-notmatch 'proposedShiftEnd'){Write-Output 'I9 R03 R05 FAIL: travel scope incomplete';exit 1}
function Remove-CSharpComments([string]$source){
 $builder=[Text.StringBuilder]::new();$state='Code';$index=0
 while($index-lt $source.Length){
  $current=$source[$index];$next=if($index+1-lt $source.Length){$source[$index+1]}else{[char]0}
  switch($state){
   'Code' {
    if($current-eq '/'-and $next-eq '/'){$state='LineComment';$index+=2;continue}
    if($current-eq '/'-and $next-eq '*'){$state='BlockComment';$index+=2;continue}
    if($current-eq '@'-and $next-eq '"'){[void]$builder.Append($current);[void]$builder.Append($next);$state='VerbatimString';$index+=2;continue}
    [void]$builder.Append($current)
    if($current-eq '"'){$state='String'}elseif($current-eq "'"){$state='Character'}
    $index++;continue
   }
   'LineComment' {if($current-eq "`n"){[void]$builder.Append($current);$state='Code'};$index++;continue}
   'BlockComment' {if($current-eq '*'-and $next-eq '/'){$state='Code';$index+=2;continue};if($current-eq "`n"){[void]$builder.Append($current)};$index++;continue}
   'String' { [void]$builder.Append($current);if($current-eq '\'-and $index+1-lt $source.Length){$index++;[void]$builder.Append($source[$index])}elseif($current-eq '"'){$state='Code'};$index++;continue }
   'Character' { [void]$builder.Append($current);if($current-eq '\'-and $index+1-lt $source.Length){$index++;[void]$builder.Append($source[$index])}elseif($current-eq "'"){$state='Code'};$index++;continue }
   'VerbatimString' { [void]$builder.Append($current);if($current-eq '"'-and $next-eq '"'){[void]$builder.Append($next);$index+=2;continue};if($current-eq '"'){$state='Code'};$index++;continue }
  }
 }
 return $builder.ToString()
}
function Test-ExceptionRouteContract([string]$section){
 $normalized=(Remove-CSharpComments $section)-replace '\s',''
 $authorization='authorization.RequireAsync("SCHEDULING","APPROVE_EXCEPTION",ct)'
 $deniedReturn='if(deniedisnotnull)returndenied;'
 $mutation='repository.CreateScheduleExceptionAsync('
 $authorizationIndex=$normalized.IndexOf($authorization,[StringComparison]::Ordinal)
 $deniedIndex=$normalized.IndexOf($deniedReturn,[StringComparison]::Ordinal)
 $mutationIndex=$normalized.IndexOf($mutation,[StringComparison]::Ordinal)
 return $authorizationIndex-ge 0-and $deniedIndex-gt $authorizationIndex-and $mutationIndex-gt $deniedIndex
}
$portalSource=Get-Content $authorizationBoundary -Raw
$routeMarker='app.MapPost("/api/portal/scheduling/proposals/{versionId:long}/exceptions"'
$nextRouteMarker='app.MapPost("/api/portal/scheduling/proposals/{versionId:long}/approve"'
$routeStart=$portalSource.IndexOf($routeMarker,[StringComparison]::Ordinal)
$routeEnd=if($routeStart-ge 0){$portalSource.IndexOf($nextRouteMarker,$routeStart,[StringComparison]::Ordinal)}else{-1}
if($routeStart-lt 0-or $routeEnd-le $routeStart){Write-Output 'I9 R03 R05 BLOCKED: exact exception route unavailable';exit 2}
$exceptionRoute=$portalSource.Substring($routeStart,$routeEnd-$routeStart)
if(-not(Test-ExceptionRouteContract $exceptionRoute)){Write-Output 'I9 R03 R05 BLOCKED: authorization must precede denied return and repository mutation';exit 2}
$normalizedRoute=(Remove-CSharpComments $exceptionRoute)-replace '\s',''
$authorizationMarker='authorization.RequireAsync("SCHEDULING","APPROVE_EXCEPTION",ct)'
$deniedReturnMarker='if(deniedisnotnull)returndenied;'
$mutationMarker='repository.CreateScheduleExceptionAsync('
$withoutAuthorization=$normalizedRoute.Replace($authorizationMarker,'')
$withoutDeniedReturn=$normalizedRoute.Replace($deniedReturnMarker,'')
$reordered=$withoutDeniedReturn.Replace($mutationMarker,$mutationMarker+$deniedReturnMarker)
$permissionOnlyInComment=$normalizedRoute.Replace($authorizationMarker,"/*$authorizationMarker*/")
$returnOnlyInComment=$normalizedRoute.Replace($deniedReturnMarker,"//$deniedReturnMarker`n")
$mutationBeforeAuthorization=$mutationMarker+$authorizationMarker+$deniedReturnMarker
if((Test-ExceptionRouteContract $withoutAuthorization)-or(Test-ExceptionRouteContract $reordered)-or
   (Test-ExceptionRouteContract $permissionOnlyInComment)-or(Test-ExceptionRouteContract $returnOnlyInComment)-or
   (Test-ExceptionRouteContract $mutationBeforeAuthorization)){Write-Output 'I9 R03 R05 FAIL: authorization contract negative self-test';exit 1}
Write-Output 'R05-T12 ROUTE LINKAGE PASS'
Write-Output 'I9 R03 R05 STATIC PASS'
$dotnet='C:\tmp\dotnet6\dotnet.exe';if(-not(Test-Path $dotnet -PathType Leaf)){Write-Output 'I9 R03 R05 BLOCKED: dotnet unavailable';exit 2}
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('sg-r0305-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $tmp|Out-Null
try{
 $links=@($files|%{[Security.SecurityElement]::Escape($_)})
 $authorizationLink=[Security.SecurityElement]::Escape($authorizationService)
@"
<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net6.0</TargetFramework><LangVersion>latest</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App"/><PackageReference Include="Npgsql" Version="6.0.10"/><Using Include="Microsoft.Extensions.Configuration"/><Using Include="Microsoft.AspNetCore.Http"/><Compile Include="$($links[0])" Link="Models.cs"/><Compile Include="$($links[1])" Link="Validator.cs"/><Compile Include="$($links[2])" Link="WorkRest.cs"/><Compile Include="$($links[3])" Link="Overlap.cs"/><Compile Include="$($links[4])" Link="Evaluator.cs"/><Compile Include="$authorizationLink" Link="PortalAuthorizationService.cs"/></ItemGroup></Project>
"@|Set-Content (Join-Path $tmp 'H.csproj') -Encoding utf8
@'
namespace Sg.SuperApp.Api.Services;
public sealed record HarnessUser(long Id);
public sealed class RequestUserContext { public HarnessUser? User { get; set; } }
public sealed class PostgresPortalRepository
{
    private readonly bool _allowed;
    public PostgresPortalRepository(bool allowed) { _allowed = allowed; }
    public int PermissionCalls { get; private set; }
    public long? LastUserId { get; private set; }
    public string? LastModuleCode { get; private set; }
    public string? LastActionCode { get; private set; }
    public Task<bool> HasPermissionAsync(long userId, string moduleCode, string actionCode, CancellationToken cancellationToken = default)
    {
        PermissionCalls++;
        LastUserId = userId;
        LastModuleCode = moduleCode;
        LastActionCode = actionCode;
        return Task.FromResult(_allowed);
    }
}
'@|Set-Content (Join-Path $tmp 'AuthStubs.cs') -Encoding utf8
@'
using System.Globalization; using System.Text.Json; using System.Text.RegularExpressions; using Microsoft.AspNetCore.Http; using Microsoft.Extensions.DependencyInjection; using Sg.SuperApp.Api.Domain; using Sg.SuperApp.Api.Services;
static JsonElement J(string s){using var d=JsonDocument.Parse(s);return d.RootElement.Clone();}
const string A="I9-R03",B="I9-R05"; var e=new SchedulingRuleEvaluator();
var p3=J("{\"intervalSemantics\":\"HALF_OPEN\",\"adjacentIntervalsOverlap\":false}");var p5=J("{\"missingRelationOutcome\":\"EXCEPTION_REQUIRED\",\"neverAssumeZero\":true,\"directional\":true}");
var m=J("{\"matrixDemo\":[{\"from\":\"PROJECT-A/POSITION-1\",\"to\":\"PROJECT-B/POSITION-2\",\"minutes\":45,\"prohibited\":false},{\"from\":\"PROJECT-B/POSITION-2\",\"to\":\"PROJECT-A/POSITION-1\",\"minutes\":60,\"prohibited\":false},{\"from\":\"PROJECT-A/POSITION-1\",\"to\":\"PROJECT-C/POSITION-3\",\"minutes\":null,\"prohibited\":true}]}");
SchedulingRuleProfile P(JsonElement? c=null,bool on3=true,bool on5=true,int v=1)=>new(19,"MVP",v,SchedulingRuleOrigin.SIMULATED,SchedulingEnvironmentScope.MVP_TEST,"PROJECT-A",new DateOnly(2026,1,1),null,SchedulingRuleProfileStatus.ACTIVE,new string((char)('a'+v),64),new[]{new SchedulingRuleProfileEntry(A,p3,J("{}"),on3),new SchedulingRuleProfileEntry(B,p5,c??m,on5)});
SchedulingRuleEvaluationBatch E(string f,SchedulingRuleProfile? p=null,IReadOnlySet<string>? h=null)=>e.Evaluate(p??P(),"PROJECT-A",new DateOnly(2026,8,17),J(f),h);RuleEvaluation R(SchedulingRuleEvaluationBatch x,string c)=>x.Evaluations.Single(y=>y.RuleCode==c);
void Q<T>(T x,T y,string n)where T:notnull{if(!EqualityComparer<T>.Default.Equals(x,y))throw new Exception($"{n}: {x}!={y}");} SchedulingRuleSeverity S(SchedulingRuleOutcome o)=>o==SchedulingRuleOutcome.COMPLIANT?SchedulingRuleSeverity.INFO:o==SchedulingRuleOutcome.EXCEPTION_REQUIRED?SchedulingRuleSeverity.WARNING:SchedulingRuleSeverity.BLOCKING;
async Task<int> HttpStatus(IResult result){using var services=new ServiceCollection().AddLogging().BuildServiceProvider();var context=new DefaultHttpContext{RequestServices=services};await result.ExecuteAsync(context);return context.Response.StatusCode;}
void C(RuleEvaluation x,SchedulingRuleOutcome o,string c,string n){Q(o,x.Outcome,n+" outcome");Q(S(o),x.Severity,n+" severity");Q(o==SchedulingRuleOutcome.EXCEPTION_REQUIRED,x.ExceptionAllowed,n+" exception");Q(c,x.MessageCode,n+" code");Q(false,string.IsNullOrWhiteSpace(x.Explanation),n+" explanation");if(!Regex.IsMatch(x.ScopeHash,"^[a-f0-9]{64}$"))throw new Exception(n+" hash");}
// A disabled rule must still report, must not accredit compliance, and must keep the gate shut.
void D(SchedulingRuleEvaluationBatch x,string code,string n){var d=R(x,code);Q(SchedulingRuleOutcome.WARNING,d.Outcome,n+" disabled outcome");Q(SchedulingRuleSeverity.ERROR,d.Severity,n+" disabled severity");Q(code.Replace("-","_")+"_DISABLED_UNVERIFIED",d.MessageCode,n+" disabled code");Q(false,d.ExceptionAllowed,n+" disabled exception");Q(2,x.Summary.Total,n+" total");Q(1,x.Summary.Compliant,n+" compliant");Q(0,x.Summary.Blocked,n+" blocked");Q(0,x.Summary.ExceptionRequired,n+" exception required");Q(1,x.Summary.Warning,n+" warning");Q(0,x.Summary.NotApplicable,n+" not applicable");Q(false,x.Summary.CanApproveOrPublish,n+" gate stays closed");}
void Sum(SchedulingRuleEvaluationBatch x,int t,int co,int bl,int ex,bool ok,string n){Q(t,x.Summary.Total,n+" total");Q(co,x.Summary.Compliant,n+" compliant");Q(bl,x.Summary.Blocked,n+" blocked");Q(ex,x.Summary.ExceptionRequired,n+" exception");Q(0,x.Summary.Warning,n+" warning");Q(0,x.Summary.NotApplicable,n+" not applicable");Q(ok,x.Summary.CanApproveOrPublish,n+" approve");}
void SameEvaluation(RuleEvaluation x,RuleEvaluation y,string n){Q(x.RuleCode,y.RuleCode,n+" rule");Q(x.ProfileVersion,y.ProfileVersion,n+" version");Q(x.Outcome,y.Outcome,n+" outcome");Q(x.Severity,y.Severity,n+" severity");Q(x.MessageCode,y.MessageCode,n+" code");Q(x.Explanation,y.Explanation,n+" explanation");Q(x.ScopeHash,y.ScopeHash,n+" hash");Q(x.ParametersSnapshot.GetRawText(),y.ParametersSnapshot.GetRawText(),n+" parameters snapshot");Q(x.FactsSnapshot.GetRawText(),y.FactsSnapshot.GetRawText(),n+" facts snapshot");Q(x.ExceptionAllowed,y.ExceptionAllowed,n+" exception");}
void SameBatch(SchedulingRuleEvaluationBatch x,SchedulingRuleEvaluationBatch y,string n){Q(x.RuleProfileId,y.RuleProfileId,n+" profile id");Q(x.ProfileCode,y.ProfileCode,n+" profile code");Q(x.ProfileVersion,y.ProfileVersion,n+" profile version");Q(x.Simulated,y.Simulated,n+" simulated");Q(x.Evaluations.Count,y.Evaluations.Count,n+" evaluations");for(var i=0;i<x.Evaluations.Count;i++)SameEvaluation(x.Evaluations[i],y.Evaluations[i],n+$" evaluation {i}");Q(x.Summary,y.Summary,n+" summary");}
string F(string g="guard-a",string asn="assignment-a",string pasn="assignment-old",string ps="2026-08-20T06:00:00-05:00",string pe="2026-08-20T07:15:00-05:00",string ns="2026-08-20T08:00:00-05:00",string ne="2026-08-20T16:00:00-05:00",string iv="[]",string from="PROJECT-A/POSITION-1",string to="PROJECT-A/POSITION-1")=>$"{{\"assignmentId\":\"{asn}\",\"previousAssignmentId\":\"{pasn}\",\"scheduleVersionId\":\"v-a\",\"employeeId\":\"{g}\",\"previousShiftStart\":\"{ps}\",\"previousShiftEnd\":\"{pe}\",\"proposedShiftStart\":\"{ns}\",\"proposedShiftEnd\":\"{ne}\",\"existingIntervals\":{iv},\"originPositionCode\":\"{from}\",\"destinationPositionCode\":\"{to}\"}}";
string I(string g,string s,string z,string st)=>$"[{{\"employeeId\":\"{g}\",\"start\":\"{s}\",\"end\":\"{z}\",\"status\":\"{st}\"}}]";const string S0="2026-08-20T08:00:00-05:00",E0="2026-08-20T16:00:00-05:00";
string Iso(DateTimeOffset value)=>value.ToString("yyyy-MM-dd'T'HH:mm:sszzz",CultureInfo.InvariantCulture);
string G(int gap,string ns="2026-08-20T08:00:00-05:00",string g="guard-a",string asn="assignment-a",string pasn="assignment-old",string iv="[]",string from="PROJECT-A/POSITION-1",string to="PROJECT-B/POSITION-2"){var proposed=DateTimeOffset.ParseExact(ns,"yyyy-MM-dd'T'HH:mm:sszzz",CultureInfo.InvariantCulture);var previousEnd=proposed.AddMinutes(-gap);return F(g,asn,pasn,Iso(previousEnd.AddHours(-1)),Iso(previousEnd),Iso(proposed),Iso(proposed.AddHours(8)),iv,from,to);}
string Row(string from,string to,string minutes,bool prohibited=false)=>$"{{\"from\":\"{from}\",\"to\":\"{to}\",\"minutes\":{(prohibited?"null":minutes)},\"prohibited\":{prohibited.ToString().ToLowerInvariant()}}}";
JsonElement Cat(params string[] rows)=>J("{\"matrixDemo\":["+string.Join(",",rows)+"]}");
var passed=0;void Done(string id){passed++;Console.WriteLine(id+" PASS");}void T(string id,string f,SchedulingRuleOutcome o3,string c3,SchedulingRuleOutcome o5,string c5,bool ok=false,SchedulingRuleProfile? p=null,IReadOnlySet<string>? h=null){var x=E(f,p,h);C(R(x,A),o3,c3,id+" R03");C(R(x,B),o5,c5,id+" R05");Sum(x,2,(o3==SchedulingRuleOutcome.COMPLIANT?1:0)+(o5==SchedulingRuleOutcome.COMPLIANT?1:0),(o3==SchedulingRuleOutcome.BLOCKED?1:0)+(o5==SchedulingRuleOutcome.BLOCKED?1:0),(o3==SchedulingRuleOutcome.EXCEPTION_REQUIRED?1:0)+(o5==SchedulingRuleOutcome.EXCEPTION_REQUIRED?1:0),ok,id);Done(id);}
/* Literal mapping: R03 T01 adjacency, T02 17:59, T03 contained, T04 equal, T05 earlier/inside, T06 midnight, T07 month end, T08 year end, T09 APPROVED, T10 DRAFT, T11 other guard, T12 distinct positions/no relation, T13 R03 precedence, T14 edit, T15 disabled. R05 T01 same post, T02 same site missing, T03-5 30-minute boundaries, T06-7 directional, T08 profile isolation, T09 unavailable, T10 prohibited, T11 approval, T12 authorization boundary, T13 scope mismatch, T14 edit, T15 precedence, T16 snapshots, T17 invalid, T18 fractional, T19 cross-year gap, T20 disabled. */
var deterministicOne=E(F());var deterministicTwo=E(F());SameBatch(deterministicOne,deterministicTwo,"deterministic double run");Console.WriteLine("DETERMINISTIC DOUBLE RUN PASS");
T("R03-T01",F(ps:"2026-08-20T16:00:00-05:00",pe:"2026-08-20T17:15:00-05:00",ns:"2026-08-20T18:00:00-05:00",ne:"2026-08-20T22:00:00-05:00",iv:I("guard-a","2026-08-20T10:00:00-05:00","2026-08-20T18:00:00-05:00","APPROVED")),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION",true);
T("R03-T02",F(ps:"2026-08-20T16:00:00-05:00",pe:"2026-08-20T17:14:00-05:00",ns:"2026-08-20T17:59:00-05:00",ne:"2026-08-20T22:00:00-05:00",iv:I("guard-a","2026-08-20T10:00:00-05:00","2026-08-20T18:00:00-05:00","APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T03",F(ns:"2026-08-20T10:00:00-05:00",ne:"2026-08-20T12:00:00-05:00",iv:I("guard-a",S0,E0,"APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T04",F(iv:I("guard-a",S0,E0,"APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T05",F(ps:"2026-08-20T04:00:00-05:00",pe:"2026-08-20T05:15:00-05:00",ns:"2026-08-20T06:00:00-05:00",ne:"2026-08-20T10:00:00-05:00",iv:I("guard-a",S0,E0,"APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T06",F(ps:"2026-08-20T21:00:00-05:00",pe:"2026-08-20T22:45:00-05:00",ns:"2026-08-20T23:30:00-05:00",ne:"2026-08-21T01:00:00-05:00",iv:I("guard-a","2026-08-20T23:45:00-05:00","2026-08-21T00:15:00-05:00","APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T07",F(ps:"2026-08-31T21:00:00-05:00",pe:"2026-08-31T22:45:00-05:00",ns:"2026-08-31T23:30:00-05:00",ne:"2026-09-01T01:00:00-05:00",iv:I("guard-a","2026-08-31T23:45:00-05:00","2026-09-01T00:15:00-05:00","APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T08",F(ps:"2026-12-31T21:00:00-05:00",pe:"2026-12-31T22:45:00-05:00",ns:"2026-12-31T23:30:00-05:00",ne:"2027-01-01T01:00:00-05:00",iv:I("guard-a","2026-12-31T23:45:00-05:00","2027-01-01T00:15:00-05:00","APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T09",F(iv:I("guard-a",S0,E0,"APPROVED")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T10",F(iv:I("guard-a",S0,E0,"DRAFT")),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_DRAFT_BLOCKED",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION");
T("R03-T11",F(iv:I("guard-b",S0,E0,"APPROVED")),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION",true);
T("R03-T12",G(0,from:"SITE-A/POSITION-1",to:"SITE-A/POSITION-2"),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_RELATION_MISSING",false,P(Cat()));
var overlapProfile=P(Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","30")));var overlapFacts=G(29,iv:I("guard-a","2026-08-20T08:00:00-05:00","2026-08-20T10:00:00-05:00","APPROVED"));var overlapPending=E(overlapFacts,overlapProfile);C(R(overlapPending,A),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED","R03-T13 pending R03");C(R(overlapPending,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R03-T13 pending R05");Sum(overlapPending,2,0,1,1,false,"R03-T13 pending");var overlapExact=new HashSet<string>{R(overlapPending,B).ScopeHash};var overlapApproved=E(overlapFacts,overlapProfile,overlapExact);C(R(overlapApproved,A),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED","R03-T13 approved R03");C(R(overlapApproved,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R03-T13 approved R05");Q(R(overlapPending,B).ScopeHash,R(overlapApproved,B).ScopeHash,"R03-T13 exact hash");Sum(overlapApproved,2,0,1,1,false,"R03-T13 approved");Done("R03-T13");
var baselineFacts=F(ps:"2026-08-20T06:00:00-05:00",pe:"2026-08-20T07:15:00-05:00",ns:"2026-08-20T16:00:00-05:00",ne:"2026-08-20T20:00:00-05:00",iv:I("guard-a",S0,E0,"APPROVED"));var baseline=E(baselineFacts);C(R(baseline,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R03-T14 baseline R03");C(R(baseline,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION","R03-T14 baseline R05");Sum(baseline,2,2,0,0,true,"R03-T14 baseline");var editedFacts=F(ps:"2026-08-20T06:00:00-05:00",pe:"2026-08-20T07:15:00-05:00",ns:"2026-08-20T15:59:00-05:00",ne:"2026-08-20T20:00:00-05:00",iv:I("guard-a",S0,E0,"APPROVED"));var edited=E(editedFacts);C(R(edited,A),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED","R03-T14 edited R03");C(R(edited,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION","R03-T14 edited R05");Q(false,R(baseline,A).ScopeHash==R(edited,A).ScopeHash,"R03-T14 new R03 hash");Sum(edited,2,1,1,0,false,"R03-T14 edited");Done("R03-T14");
var r03Disabled=E(F(),P(on3:false));D(r03Disabled,A,"R03-T15");C(R(r03Disabled,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION","R03-T15 R05");Done("R03-T15");
// R05-T01..T20: seed matrix, missing vs malformed, exact scope and temporal gap.
var row30=Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","30"));
T("R05-T01",G(0,from:"PROJECT-A/POSITION-1",to:"PROJECT-A/POSITION-1"),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.COMPLIANT,"I9_R05_SAME_POSITION",true,P(J("{}")));
T("R05-T02",G(0,from:"SITE-A/POSITION-1",to:"SITE-A/POSITION-2"),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_RELATION_MISSING",false,P(Cat()));
T("R05-T03",G(30),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT",true,P(row30));
T("R05-T04",G(31),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT",true,P(row30));
T("R05-T05",G(29),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED",false,P(row30));
var oneWayProfile=P(Cat(Row("POST-A","POST-B","30")));T("R05-T06",G(30,from:"POST-B",to:"POST-A"),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_RELATION_MISSING",false,oneWayProfile);
var directionalProfile=P(Cat(Row("POST-A","POST-B","30"),Row("POST-B","POST-A","50")));var forward=E(G(30,from:"POST-A",to:"POST-B"),directionalProfile);C(R(forward,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T07 forward R03");C(R(forward,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T07 forward R05");Sum(forward,2,2,0,0,true,"R05-T07 forward");var reverse=E(G(30,from:"POST-B",to:"POST-A"),directionalProfile);C(R(reverse,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T07 reverse R03");C(R(reverse,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T07 reverse R05");Sum(reverse,2,1,0,1,false,"R05-T07 reverse");Q(false,R(forward,B).ScopeHash==R(reverse,B).ScopeHash,"R05-T07 directional hash");Done("R05-T07");
var currentProfile=P(Cat(),v:1);var otherVersionProfile=P(row30,v:2);var versionFacts=G(30);var currentMissing=E(versionFacts,currentProfile);C(R(currentMissing,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T08 current R03");C(R(currentMissing,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_RELATION_MISSING","R05-T08 current R05");Sum(currentMissing,2,1,0,1,false,"R05-T08 current");var otherVersion=E(versionFacts,otherVersionProfile);C(R(otherVersion,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T08 other R03");C(R(otherVersion,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T08 other R05");Sum(otherVersion,2,2,0,0,true,"R05-T08 other");Q(1,currentMissing.ProfileVersion,"R05-T08 current version");Q(2,otherVersion.ProfileVersion,"R05-T08 other version");Q(false,R(currentMissing,B).ScopeHash==R(otherVersion,B).ScopeHash,"R05-T08 version hash");Done("R05-T08");
T("R05-T09",G(30),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_MATRIX_UNAVAILABLE",false,P(J("{}")));
T("R05-T10",G(30,from:"POST-A",to:"POST-B"),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.BLOCKED,"I9_R05_PROHIBITED",false,P(Cat(Row("POST-A","POST-B","0",true))));
foreach(var corruptCatalog in new[]{"null","[]","\"invalid\"","42"}){var corrupt=E(G(30),P(J(corruptCatalog)));C(R(corrupt,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","malformed top-level R03 "+corruptCatalog);C(R(corrupt,B),SchedulingRuleOutcome.BLOCKED,"I9_R05_INVALID_MATRIX","malformed top-level R05 "+corruptCatalog);Sum(corrupt,2,1,1,0,false,"malformed top-level "+corruptCatalog);}Console.WriteLine("MALFORMED TOP-LEVEL PASS");
var approvalProfile=P(row30);var approvalFacts=G(29);var approvalPending=E(approvalFacts,approvalProfile);C(R(approvalPending,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T11 pending R03");C(R(approvalPending,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T11 pending R05");Sum(approvalPending,2,1,0,1,false,"R05-T11 pending");var exactR05Approval=new HashSet<string>{R(approvalPending,B).ScopeHash};var approvalGranted=E(approvalFacts,approvalProfile,exactR05Approval);C(R(approvalGranted,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T11 approved R03");C(R(approvalGranted,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T11 approved R05");Q(R(approvalPending,B).ScopeHash,R(approvalGranted,B).ScopeHash,"R05-T11 exact approval hash");Sum(approvalGranted,2,1,0,1,true,"R05-T11 approved");Done("R05-T11");
var deniedRepository=new PostgresPortalRepository(false);var deniedAuthorization=new PortalAuthorizationService(new RequestUserContext{User=new HarnessUser(73)},deniedRepository);var forbidden=await deniedAuthorization.RequireAsync("SCHEDULING","APPROVE_EXCEPTION",CancellationToken.None);Q(false,forbidden is null,"R05-T12 authenticated denial result");Q(StatusCodes.Status403Forbidden,await HttpStatus(forbidden!),"R05-T12 authenticated denial status");Q(1,deniedRepository.PermissionCalls,"R05-T12 permission calls");Q(73L,deniedRepository.LastUserId!.Value,"R05-T12 permission user");Q("SCHEDULING",deniedRepository.LastModuleCode!,"R05-T12 permission module");Q("APPROVE_EXCEPTION",deniedRepository.LastActionCode!,"R05-T12 permission action");var anonymousRepository=new PostgresPortalRepository(true);var anonymousAuthorization=new PortalAuthorizationService(new RequestUserContext(),anonymousRepository);var unauthorized=await anonymousAuthorization.RequireAsync("SCHEDULING","APPROVE_EXCEPTION",CancellationToken.None);Q(false,unauthorized is null,"R05-T12 anonymous result");Q(StatusCodes.Status401Unauthorized,await HttpStatus(unauthorized!),"R05-T12 anonymous status");Q(0,anonymousRepository.PermissionCalls,"R05-T12 anonymous repository bypass");Done("R05-T12");
var reusedFacts=G(29,g:"guard-b",asn:"assignment-b",pasn:"assignment-old-b");var reused=E(reusedFacts,approvalProfile,exactR05Approval);C(R(reused,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T13 reused R03");C(R(reused,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T13 reused R05");Q(false,R(approvalPending,B).ScopeHash==R(reused,B).ScopeHash,"R05-T13 new guard and turn hash");Sum(reused,2,1,0,1,false,"R05-T13 reused");Done("R05-T13");
var editProfile=P(Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","30"),Row("PROJECT-A/POSITION-1","PROJECT-C/POSITION-3","30")));var beforeEditFacts=G(29,iv:I("guard-a","2026-08-20T06:00:00-05:00","2026-08-20T08:00:00-05:00","APPROVED"));var beforeEdit=E(beforeEditFacts,editProfile);C(R(beforeEdit,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T14 before R03");C(R(beforeEdit,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T14 before R05");Sum(beforeEdit,2,1,0,1,false,"R05-T14 before");var beforeEditApproval=new HashSet<string>{R(beforeEdit,B).ScopeHash};var beforeEditApproved=E(beforeEditFacts,editProfile,beforeEditApproval);C(R(beforeEditApproved,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T14 approved R03");C(R(beforeEditApproved,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T14 approved R05");Q(R(beforeEdit,B).ScopeHash,R(beforeEditApproved,B).ScopeHash,"R05-T14 exact approval hash");Sum(beforeEditApproved,2,1,0,1,true,"R05-T14 approved");var afterEditFacts=G(29,ns:"2026-08-20T07:59:00-05:00",iv:I("guard-a","2026-08-20T06:00:00-05:00","2026-08-20T08:00:00-05:00","APPROVED"),from:"PROJECT-A/POSITION-1",to:"PROJECT-C/POSITION-3");var afterEdit=E(afterEditFacts,editProfile,beforeEditApproval);C(R(afterEdit,A),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED","R05-T14 edited R03");C(R(afterEdit,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T14 edited R05");Q(false,R(beforeEdit,A).ScopeHash==R(afterEdit,A).ScopeHash,"R05-T14 new R03 hash");Q(false,R(beforeEdit,B).ScopeHash==R(afterEdit,B).ScopeHash,"R05-T14 new R05 hash");Sum(afterEdit,2,0,1,1,false,"R05-T14 edited");Done("R05-T14");
var precedenceFacts=G(29,iv:I("guard-a","2026-08-20T08:00:00-05:00","2026-08-20T10:00:00-05:00","APPROVED"));var precedencePending=E(precedenceFacts,approvalProfile);var precedenceApproval=new HashSet<string>{R(precedencePending,B).ScopeHash};var precedenceApproved=E(precedenceFacts,approvalProfile,precedenceApproval);C(R(precedenceApproved,A),SchedulingRuleOutcome.BLOCKED,"I9_R03_OVERLAP_APPROVED_BLOCKED","R05-T15 R03");C(R(precedenceApproved,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T15 R05");Q(R(precedencePending,B).ScopeHash,R(precedenceApproved,B).ScopeHash,"R05-T15 exact R05 hash");Sum(precedenceApproved,2,0,1,1,false,"R05-T15");Done("R05-T15");
var oldSnapshotProfile=P(row30,v:1);var snapshotFacts=G(25);var oldCatalogSnapshot=oldSnapshotProfile.Entries.Single(x=>x.RuleCode==B).CatalogSnapshot.GetRawText();var oldFirst=E(snapshotFacts,oldSnapshotProfile);C(R(oldFirst,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T16 old first R03");C(R(oldFirst,B),SchedulingRuleOutcome.EXCEPTION_REQUIRED,"I9_R05_EXCEPTION_REQUIRED","R05-T16 old first R05");Sum(oldFirst,2,1,0,1,false,"R05-T16 old first");var oldSecond=E(snapshotFacts,oldSnapshotProfile);SameBatch(oldFirst,oldSecond,"R05-T16 old deterministic");Q(oldCatalogSnapshot,oldSnapshotProfile.Entries.Single(x=>x.RuleCode==B).CatalogSnapshot.GetRawText(),"R05-T16 old catalog snapshot");var regeneratedProfile=P(Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","20")),v:2);var regenerated=E(snapshotFacts,regeneratedProfile);C(R(regenerated,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T16 regenerated R03");C(R(regenerated,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T16 regenerated R05");Sum(regenerated,2,2,0,0,true,"R05-T16 regenerated");Q(false,R(oldFirst,B).ScopeHash==R(regenerated,B).ScopeHash,"R05-T16 regenerated hash");Q(1,R(oldFirst,B).ProfileVersion,"R05-T16 old version");Q(2,R(regenerated,B).ProfileVersion,"R05-T16 new version");Done("R05-T16");
var negativeMinutes=E(G(30),P(Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","-1"))));C(R(negativeMinutes,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T17 negative minutes R03");C(R(negativeMinutes,B),SchedulingRuleOutcome.BLOCKED,"I9_R05_INVALID_MATRIX","R05-T17 negative minutes R05");Sum(negativeMinutes,2,1,1,0,false,"R05-T17 negative minutes");var negativeGap=E(G(-1),approvalProfile);C(R(negativeGap,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T17 negative gap R03");C(R(negativeGap,B),SchedulingRuleOutcome.BLOCKED,"I9_R05_INVALID_GAP","R05-T17 negative gap R05");Sum(negativeGap,2,1,1,0,false,"R05-T17 negative gap");Done("R05-T17");
T("R05-T18",G(30),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT",SchedulingRuleOutcome.BLOCKED,"I9_R05_INVALID_MATRIX",false,P(Cat(Row("PROJECT-A/POSITION-1","PROJECT-B/POSITION-2","30.5"))));
var midnight=E(G(30,ns:"2026-08-21T00:00:00-05:00"),approvalProfile);C(R(midnight,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T19 midnight R03");C(R(midnight,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T19 midnight R05");Sum(midnight,2,2,0,0,true,"R05-T19 midnight");var month=E(G(30,ns:"2026-09-01T00:00:00-05:00"),approvalProfile);C(R(month,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T19 month R03");C(R(month,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T19 month R05");Sum(month,2,2,0,0,true,"R05-T19 month");var year=E(G(30,ns:"2027-01-01T00:00:00-05:00"),approvalProfile);C(R(year,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T19 year R03");C(R(year,B),SchedulingRuleOutcome.COMPLIANT,"I9_R05_COMPLIANT","R05-T19 year R05");Sum(year,2,2,0,0,true,"R05-T19 year");Q(false,R(midnight,B).ScopeHash==R(month,B).ScopeHash,"R05-T19 midnight/month hash");Q(false,R(month,B).ScopeHash==R(year,B).ScopeHash,"R05-T19 month/year hash");Done("R05-T19");
var r05Disabled=E(G(30),P(row30,on5:false));D(r05Disabled,B,"R05-T20");C(R(r05Disabled,A),SchedulingRuleOutcome.COMPLIANT,"I9_R03_COMPLIANT","R05-T20 R03");Done("R05-T20");Q(35,passed,"numbered scenario count");Console.WriteLine($"I9 R03 R05 PASS {passed}");Console.WriteLine("I9 R03 R05 PASS");
'@|Set-Content (Join-Path $tmp 'Program.cs') -Encoding utf8
 & $dotnet run --project (Join-Path $tmp 'H.csproj') --configuration Release;exit $LASTEXITCODE
}finally{if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force}}
