param([string]$ApiBaseUrl="http://localhost:5080/api",[long]$VersionId=1,[string]$VerificationSchema,[string]$Database="sg_superapp_dev",[string]$AppPassword="sg_app_change_me")
$ErrorActionPreference="Stop"
function Call($body){try{$r=Invoke-WebRequest -UseBasicParsing -Uri "$ApiBaseUrl/portal/scheduling/versions/$VersionId/replan" -Method Post -Headers $script:headers -ContentType "application/json" -Body ($body|ConvertTo-Json -Depth 6);@{Status=[int]$r.StatusCode;Body=($r.Content|ConvertFrom-Json)}}catch{if($null-eq$_.Exception.Response){throw};@{Status=[int]$_.Exception.Response.StatusCode;Body=$null}}}
$login=Invoke-RestMethod -Uri "$ApiBaseUrl/auth/login" -Method Post -ContentType "application/json" -Body (@{username="operaciones.sg";password="Operaciones123"}|ConvertTo-Json);$script:headers=@{Authorization="Bearer $($login.sessionToken)"}
if($VerificationSchema){if($VerificationSchema-cnotmatch '^sg_i9_replan_[0-9]+_[0-9]{17}\z'){throw "Unsafe verification schema."};$oldP=$env:PGPASSWORD;$oldO=$env:PGOPTIONS;try{$env:PGPASSWORD=$AppPassword;$env:PGOPTIONS="-c search_path=$VerificationSchema,public";$q='C:\Program Files\PostgreSQL\18\bin\psql.exe';&$q -X -q -h localhost -U sg_app -d $Database -c "insert into schedule_exceptions(schedule_version_id,exception_type,reason,responsible) values($VersionId,'SUBSANABLE','Proxima a vencer','operaciones.sg');insert into schedule_versions(schedule_id,version_number,status,created_by) select schedule_id,version_number+1,'PROPUESTA','operaciones.sg' from schedule_versions where id=$VersionId";if($LASTEXITCODE){throw "Could not prepare notification fixtures."}}finally{$env:PGPASSWORD=$oldP;$env:PGOPTIONS=$oldO}}
$body=@{triggerType="ABSENCE";triggerId="absence-guard-1";modes=@("MINIMUM_IMPACT","GLOBAL")}
$first=Call $body;if($first.Status-eq 404){throw "I9 replanning endpoint is missing (HTTP 404)."};if($first.Status-ne 200){throw "Replanning returned HTTP $($first.Status)."}
$scenarios=@($first.Body.scenarios);if($scenarios.Count-ne 2){throw "Expected two replanning scenarios."}
$minimum=$scenarios|Where-Object mode -eq "MINIMUM_IMPACT";$global=$scenarios|Where-Object mode -eq "GLOBAL"
if($null-eq$minimum-or$null-eq$global){throw "Missing minimum/global scenario."};if($minimum.changedAssignments-gt$global.changedAssignments){throw "Minimum impact changed more assignments than global."}
foreach($s in $scenarios){foreach($field in @('changedAssignments','additionalHours','vacancies','exceptions')){if($null-eq$s.$field){throw "Scenario missing $field."}}}
$second=Call $body;if($second.Status-ne 200-or($first.Body|ConvertTo-Json -Depth 8 -Compress)-cne($second.Body|ConvertTo-Json -Depth 8 -Compress)){throw "Replanning is not deterministic/idempotent."}
if($VerificationSchema){$oldP=$env:PGPASSWORD;$oldO=$env:PGOPTIONS;try{$env:PGPASSWORD=$AppPassword;$env:PGOPTIONS="-c search_path=$VerificationSchema,public";$q='C:\Program Files\PostgreSQL\18\bin\psql.exe';$state=&$q -X -q -t -A -h localhost -U sg_app -d $Database -c "select count(*),count(distinct deduplication_key),count(*) filter(where source_module='SCHEDULING') from notification_items where deduplication_key like 'SCHEDULING:%'";if($LASTEXITCODE-ne 0-or$state.Trim()-ne'4|4|4'){throw "Scheduling notifications are not deduplicated: $state"}}finally{$env:PGPASSWORD=$oldP;$env:PGOPTIONS=$oldO}}
Write-Host "I9 REPLANNING PASS"
